---
title: "My Projects"
---

# Final Project for CELL 6351 Course – Intro to Reproducible Data Analysis Using R


## Project Story and Motivation

In 2023, I joined the Csiszar and Ungvari Vascular Cognitive Impairment and Dementia research group in the Department of Neurosurgery at the University of Oklahoma Health Sciences Center. **My research focused on using whole-brain irradiation as an experimental tool to induce cellular senescence and model features of accelerated brain aging**.

Before I joined the project, our laboratory primarily used a cesium-137 gamma irradiator for whole-brain irradiation studies. However, as part of a national effort to reduce the security risks associated with high-activity cesium-137 sources, our institution transitioned to a Precision X-Ray irradiator. This transition created both a challenge and an opportunity: the existing irradiation protocol could not simply be transferred to the new system without careful testing, optimization, and validation.

*I completed the required Radiation Safety Training and collaborated with the Radiation Oncology Department to establish a safe and reproducible whole-brain X-ray irradiation protocol. Over approximately 24 months, we evaluated irradiation settings, positioning methods, shielding, dose delivery, safety procedures, and fractionation schedules. Our objective was not only to generate experimental data, but also to develop a clinically relevant protocol that could be reproduced and incorporated into a formal standard operating procedure*


[**Request Access to the Final Report - Currently Under Review**](mailto:Sivasai-chandragiri@ou.edu?subject=Request%20for%20Final%20Report)


---

## Coming SOON:

- Conference posters
- Publications
- Data visualizations
- Analysis write-ups
- Project proposals
